# Generated by Django 5.0.4 on 2024-05-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='vehicle_images/')),
                ('rent_price_per_day', models.DecimalField(decimal_places=2, max_digits=8)),
                ('available_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
operations = [
  
    migrations.AddField(
        model_name='Booking',
        name='price',
        field=models.DecimalField(default=0, max_digits=10, decimal_places=2),
    ),
  
]
