# Generated by Django 5.0.4 on 2024-05-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_car_image',
            field=models.ImageField(blank=True, null=True, upload_to='booking_images/'),
        ),
    ]
