# Generated by Django 5.0.4 on 2024-05-29 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0004_booking_booked_car_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booked_car_name',
        ),
    ]
