# Generated by Django 5.0.4 on 2024-05-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0005_remove_booking_booked_car_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='owner',
            field=models.CharField(default='', max_length=100),
        ),
    ]
