# Generated by Django 5.0.4 on 2024-06-17 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0007_rentalbooking'),
    ]

    operations = [
    ]
