# Generated by Django 5.0.4 on 2024-06-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0008_auto_20240618_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
